### PR TITLE
Support Amazon Linux 2023

### PR DESCRIPTION
**Pull request by himani2411**
### Description of changes
* PR to run Install and Config kitchen tests after changes from https://github.com/aws/aws-parallelcluster-cookbook/pull/2343
* See commit descriptions for details

### Tests
AMIs build are successful. All integration tests in develop.yaml have been run.
Only the following 6 tests are **failing**:
```
test-suites:
  basic:
    test_essential_features.py::test_essential_features:
      dimensions:
      - instances:
        - c5.xlarge
        oss:
        - alinux2023
        regions:
        - us-east-1
        schedulers:
        - slurm
  createami:
    test_createami.py::test_build_image_custom_components:
      dimensions:
      - instances:
        - m6g.xlarge
        oss:
        - alinux2023
        regions:
        - us-west-1
      - instances:
        - c5.xlarge
        oss:
        - alinux2023
        regions:
        - eu-north-1
  iam:
    test_iam_image.py::test_iam_roles:
      dimensions:
      - instances:
        - c5.xlarge
        oss:
        - alinux2023
        regions:
        - us-west-2
  networking:
    test_cluster_networking.py::test_cluster_in_no_internet_subnet:
      dimensions:
      - instances:
        - c5.xlarge
        oss:
        - alinux2023
        regions:
        - us-east-1
        schedulers:
        - slurm
  trainium:
    test_trainium.py::test_trainium:
      dimensions:
      - oss:
        - alinux2023
        regions:
        - us-west-2
        schedulers:
        - slurm

```

### References
* CLI PR https://github.com/aws/aws-parallelcluster/pull/6223

### Checklist
- Make sure you are pointing to **the right branch**.
- If you're creating a patch for a branch other than `develop` add the branch name as prefix in the PR title (e\.g\. `[release-3.6]`).
- Check all commits' messages are clear, describing what and why vs how.
- Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by himani2411 — COMMENTED** [review]
I am not sure whether we require this specific commit or not as the `[TEMP]` taggged commits were something that I was adding to find a solution to few errors that I was getting 

https://github.com/aws/aws-parallelcluster-cookbook/pull/2692/commits/84e0d192155a62c6ac5a594e283c72ec685b4f57

https://github.com/aws/aws-parallelcluster-cookbook/pull/2692/commits/7cf55fd0fb4ade084b1cae73c576cbda690be604

File: cookbooks/aws-parallelcluster-computefleet/metadata.rb [hunk 1]
```diff
@@ -9,7 +9,7 @@
 chef_version '>= 18'
 version '3.10.0'
 
-supports 'amazon', '= 2.0'
+supports 'amazon', '>= 2.0'
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-computefleet/metadata.rb]: Why not using a more precise constraint?
```
supports 'amazon', '= 2.0'
supports 'amazon', '= 2023'
```

File: cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml [hunk 2]
```diff
@@ -113,16 +113,6 @@ suites:
     verifier:
       controls:
         - tag:install_cfnbootstrap_virtualenv_created
-  - name: cfnconfig_mixed
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml:116]: Why necessary to remove this?

File: cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_alinux2023.rb [hunk 3]
```diff
@@ -0,0 +1,27 @@
+# frozen_string_literal: true
+
+#
+# Copyright:: 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_alinux2023.rb]: Copyright year must be changed (2023->2024)

File: cookbooks/aws-parallelcluster-environment/test/controls/efs_spec.rb [hunk 4]
```diff
@@ -10,7 +10,7 @@
     its('owner') { should eq 'root' }
     its('group') { should eq 'root' }
     its('mode') { should cmp '0644' }
-  end unless os_properties.alinux2?
+  end unless os_properties.alinux2? || os_properties.alinux2023?
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-environment/test/controls/efs_spec.rb]: Why not using `os_properties.alinux?` to avoid the OR statement?

File: cookbooks/aws-parallelcluster-environment/test/controls/lustre_spec.rb [hunk 5]
```diff
@@ -72,12 +72,14 @@
...
 
-  if os_properties.alinux2?
+  if os_properties.alinux?
     describe package('lustre-client') do
       it { should be_installed }
       its('version') { should cmp >= minimal_lustre_client_version }
     end
+  end
 
+  if os_properties.alinux2?
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-environment/test/controls/lustre_spec.rb:82]: Did you double check that AL2023 does not require any extras repo?

File: cookbooks/aws-parallelcluster-environment/test/controls/system_authentication_spec.rb [hunk 6]
```diff
@@ -35,7 +35,7 @@
 
   services = %w(sssd)
 
-  if os_properties.redhat8?
+  if os_properties.redhat?
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-environment/test/controls/system_authentication_spec.rb]: How is this change related to AL2023?

File: cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml [hunk 7]
```diff
@@ -309,3 +309,13 @@ suites:
     verifier:
       controls:
         - /tag:install_users/
+  - name: enable_services
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml]: How is this change related to AL2023?

Comment (gmarciani) [reply cookbooks/aws-parallelcluster-platform/kitchen.platform-install.yml]: Understood: new recipe added for AL2023

File: cookbooks/aws-parallelcluster-platform/spec/unit/recipes/enable_services_spec.rb [hunk 8]
```diff
@@ -0,0 +1,16 @@
+require 'spec_helper'
+
+describe 'aws-parallelcluster-platform::enable_services' do
+  for_all_oses do |platform, version|
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-platform/spec/unit/recipes/enable_services_spec.rb]: Isn't the enable:Services recipe meant for AL2023 only?

File: cookbooks/aws-parallelcluster-platform/test/controls/enable_services_spec.rb [hunk 9]
```diff
@@ -0,0 +1,9 @@
+control 'tag:install_service_is_enabled' do
+  only_if { !os_properties.on_docker? }
+
+  describe service('rsyslog') do
+    it { should be_installed }
+    it { should be_enabled }
+    # it { should be_running }
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-platform/test/controls/enable_services_spec.rb]: why is this assertion commented out?

File: cookbooks/aws-parallelcluster-platform/recipes/install/enable_services.rb [hunk 10]
```diff
@@ -0,0 +1,27 @@
+# frozen_string_literal: true
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-platform/recipes/install/enable_services.rb]: Where is this recipe included?

File: cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb [hunk 11]
```diff
@@ -50,17 +50,26 @@
...
 
   if set_compiler?
-    package "gcc10" do
+    package compiler_version do
       retries 10
       retry_delay 5
     end
-    cookbook_file 'dkms/nvidia.conf' do
-      source 'dkms/nvidia.conf'
+    # TODO: Move to install_packages_alinux2023
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb]: why not moved?

File: cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb [hunk 12]
```diff
@@ -54,7 +54,7 @@
 
 control 'tag:install_dcv_installed' do
   title 'Check dcv is installed'
-  only_if { !os_properties.redhat_on_docker? && !(os_properties.ubuntu? && os_properties.arm?) }
+  only_if { !os_properties.redhat_on_docker? && !(os_properties.ubuntu? && os_properties.arm?) && !os_properties.alinux2023? }
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb:57]: what about having a 'is_dcv_supported'? to prevent the redefinition of the conditions and improve readability?

File: cookbooks/aws-parallelcluster-shared/libraries/test.rb [hunk 13]
```diff
@@ -10,3 +10,7 @@ def redhat_on_docker?
 def rocky_on_docker?
   on_docker? && platform?('rocky')
 end
+
+def alinux2023_on_docker?
+  on_docker? && platform?('amazon') && node['platform_version'].to_i == 2023
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-shared/libraries/test.rb:15]: Can't `platform?('amazon') && node['platform_version'].to_i == 2023` be replaced by `os_properties.alinux2023?`?

File: cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_alinux2023.rb [hunk 14]
```diff
@@ -0,0 +1,29 @@
...
+
+provides :dns_domain, platform: 'amazon' do |node|
+  node['platform_version'].to_i == 2023
+end
+
+use 'partial/_dns_domain_common'
+
+def search_domain_config_path
+  # Configure resolved to automatically append Route53 search domain in resolv.conf.
+  # On Ubuntu18 resolv.conf is managed by systemd-resolved.
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_alinux2023.rb]: Why mentioning Ubuntu here? I think we can remove

File: cookbooks/aws-parallelcluster-slurm/resources/mysql_client/partial/_setup_rhel_based.rb [hunk 15]
```diff
@@ -49,6 +49,8 @@ def package_platform
     platform_version = node['platform_version'].to_i
     if platform_version == 2
       platform_version = 7
+    elsif platform_version == 2023
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-slurm/resources/mysql_client/partial/_setup_rhel_based.rb:52]: Bad practice: redefinition of the same variable with different meaning.
Here we should have `platform_version` and `mysql_platform_version`

File: cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_alinux2023.rb [hunk 16]
```diff
@@ -0,0 +1,41 @@
...
+use 'partial/_slurm_dependencies_common'
+
+def dependencies
+  %w(json-c-devel perl perl-Switch lua-devel dbus-devel)
+end
+
+def unsupported_dependencies
+  # Using `sudo dnf supportinfo --pkg <PACKAGE_NAME>` to find if packages are available
+  %w(http-parser-devel)
+  # Tried replacing http-parser with below Packages ( doesnt work )
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_alinux2023.rb]: IS this verification true of just a copy paste.?What would be the advantage of using the commented out packages?

File: kitchen/kitchen.run-hook.sh [hunk 17]
```diff
@@ -37,6 +37,10 @@ if [ -e "${SCRIPT}" ]; then
         TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600") \
         && curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-id
       ')
+      echo "Install libxcrypt-compat dmidecode package by using SSH key: ${KITCHEN_SSH_KEY_PATH}"
```
Comment (gmarciani) [inline kitchen/kitchen.run-hook.sh:40]: If this is something required only by AL2023, let's add a comment saying that. 
If this is not, why adding it now?

File: util/cinc-install.sh [hunk 18]
```diff
@@ -468,8 +468,14 @@ elif test -f "/etc/Eos-release"; then
 elif test -f "/etc/redhat-release"; then
   platform=`sed 's/^\(.\+\) release.*/\1/' /etc/redhat-release | tr '[A-Z]' '[a-z]'`
   platform_version=`sed 's/^.\+ release \([.0-9]\+\).*/\1/' /etc/redhat-release`
-
-  if test "$platform" = "xenserver"; then
+  
+  if test "$platform" = "rocky linux"; then
```
Comment (gmarciani) [inline util/cinc-install.sh]: How is this change related to AL2023?

File: cookbooks/aws-parallelcluster-platform/recipes/install/enable_services.rb (hunk 10 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-platform/recipes/install/enable_services.rb]: Great finding! I moved the logic to `cloudwatch_alinux2023`

File: cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_alinux2023.rb (hunk 3 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-environment/resources/ec2_udev_rules/ec2_udev_rules_alinux2023.rb]: Done

File: cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml (hunk 2 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml:116]: Because the same test is done in kitchen.environment-config.yml. The test was repetitive

File: cookbooks/aws-parallelcluster-environment/test/controls/efs_spec.rb (hunk 4 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-environment/test/controls/efs_spec.rb]: Done

File: cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_alinux2023.rb (hunk 14 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-slurm/resources/dns_domain/dns_domain_alinux2023.rb]: Correct the comment.
Basically, Amazon Linux 2023 and Ubuntu use the same tool. Amazon Linux 2 and RHEL use the same tool

File: cookbooks/aws-parallelcluster-environment/test/controls/lustre_spec.rb (hunk 5 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-environment/test/controls/lustre_spec.rb:82]: We don't configure the extras repo. Lustre installation configures it
I checked and the extra repo is not required on al2023:
On al2:
```
$ sudo yum repolist
Loaded plugins: dkms-build-requires, extras_suggestions, langpacks, priorities,
              : update-motd, versionlock
256 packages excluded due to repository priority protections
repo id                         repo name                             status
!amzn2-core/2/x86_64            Amazon Linux 2 core repository            35,276
amzn2extra-R3.4/2/x86_64        Amazon Extras repo for R3.4                   57
amzn2extra-docker/2/x86_64      Amazon Extras repo for docker                109
amzn2extra-epel/2/x86_64        Amazon Extras repo for epel                    1
amzn2extra-kernel-5.10/2/x86_64 Amazon Extras repo for kernel-5.10           524
amzn2extra-lustre/2/x86_64      Amazon Extras repo for lustre                  4
epel/x86_64                     Extra Packages for Enterprise Linux 7 13,535+256
repolist: 49,506
```
On al2023:
```
sudo yum repolist
repo id                   repo name
amazonlinux               Amazon Linux 2023 repository
kernel-livepatch          Amazon Linux 2023 Kernel Livepatch repository
```

File: util/cinc-install.sh (hunk 18 above)
Comment (himani2411) [reply util/cinc-install.sh]: Initially when I added changes in cinc-install.sh it was for both Al2023 and Rocky linux, but after a team discussion we decided to not upgrade for rocky in cinc-install.

However, I had already upgraded cinc-install script as part of https://github.com/aws/aws-parallelcluster-cookbook/pull/2712

File: cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_alinux2023.rb (hunk 16 above)
Comment (himani2411) [reply cookbooks/aws-parallelcluster-slurm/resources/slurm_dependencies/slurm_dependencies_alinux2023.rb]: This was me trying to keep an array of dependencies which I couldnt find in AL2023 repo's. 
I wanted to track these dependencies in the code rather than removing them as later if they are supported we dont have to scramble to compare the code with different OS to know which dependency is missing.

File: util/cinc-install.sh (hunk 18 above)
Comment (himani2411) [reply util/cinc-install.sh]: So we can remove this piece of code for rocky

File: cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml (hunk 2 above)
Comment (himani2411) [reply cookbooks/aws-parallelcluster-environment/kitchen.environment-install.yml:116]: There are no tests with control `tag:install_cfnconfig`. The test we have is with control `tag:config_cfnconfig` which is being taken care in `kitchen.environment-config.yml`

File: cookbooks/aws-parallelcluster-computefleet/metadata.rb (hunk 1 above)
Comment (himani2411) [reply cookbooks/aws-parallelcluster-computefleet/metadata.rb]: I was following the same syntax we used fr ubuntu `supports 'ubuntu', '>= 20.04'`

Why do you suggest 2 different supports for AL2 and AL2023?

Comment (himani2411) [reply cookbooks/aws-parallelcluster-computefleet/metadata.rb]: I guess a precise one would block us from future AL releases.

File: cookbooks/aws-parallelcluster-slurm/resources/mysql_client/partial/_setup_rhel_based.rb (hunk 15 above)
Comment (himani2411) [reply cookbooks/aws-parallelcluster-slurm/resources/mysql_client/partial/_setup_rhel_based.rb:52]: Here we are using the `platform_version` is just the location in our s3 bucket where we archive the packages we want. Similar to what we do for Cinc-client.

```
archives/mysql/el/9/x86_64/mysql-community-client-*tar.gz
```

File: cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb (hunk 11 above)
Comment (himani2411) [reply cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb]: This comment is no longer relevant, during development I added this as I thought we should install these anyway.
However, As these packages are required only in case of we install NVIDIA, I dont see the relevance of adding them by default.

File: cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_alinux2023.rb [hunk 19]
```diff
@@ -0,0 +1,34 @@
...
+use 'partial/_cloudwatch_common'
+use 'partial/_cloudwatch_install_package_rhel'
+
+action :cloudwatch_prerequisite do
+  package "gnupg2-full" do
+    options '--allowerasing'
+    retries 3
+    retry_delay 5
+  end
+end
```
Comment (hanwen-pcluste) [inline cookbooks/aws-parallelcluster-environment/resources/cloudwatch/cloudwatch_alinux2023.rb]: This change is from https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2022.0.20220824.html

File: cookbooks/aws-parallelcluster-environment/files/alinux2023/network_interfaces/configure_nw_interface.sh [hunk 20]
```diff
@@ -0,0 +1,53 @@
...
+metric="100${DEVICE_NUMBER}"
+
+# Rename connection
+original_con_name=`nmcli -t -f GENERAL.CONNECTION device show ${DEVICE_NAME} | cut -f2 -d':'`
+sudo nmcli connection modify "${original_con_name}" con-name "${con_name}" ifname ${DEVICE_NAME}
+
+configured_ip=`nmcli -t -f IP4.ADDRESS device show ${DEVICE_NAME} | cut -f2 -d':'`
+if [ -z "${configured_ip}" ]; then
+  # Setup connection method to "manual", configure ip address and gateway, only if not already configured.
+  sudo nmcli connection modify "${con_name}" ipv4.method manual ipv4.addresses ${DEVICE_IP_ADDRESS}/${CIDR_PREFIX_LENGTH} ipv4.gateway ${GW_IP_ADDRESS}
```
Comment (enrico-usai) [inline cookbooks/aws-parallelcluster-environment/files/alinux2023/network_interfaces/configure_nw_interface.sh]: According to this comment `nmcli` is not supported: https://github.com/aws/aws-parallelcluster/pull/6223/files#r1630201744

File: cookbooks/aws-parallelcluster-platform/spec/unit/recipes/enable_services_spec.rb (hunk 8 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-platform/spec/unit/recipes/enable_services_spec.rb]: Removed after refactoring the code

File: cookbooks/aws-parallelcluster-platform/test/controls/enable_services_spec.rb (hunk 9 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-platform/test/controls/enable_services_spec.rb]: Removed after refactoring the code

File: cookbooks/aws-parallelcluster-computefleet/metadata.rb (hunk 1 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-computefleet/metadata.rb]: I removed these sections because they are not used by anything. (e.g. we forgot to change this when supporting RHEL9 and nothing was broken)

File: cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb (hunk 11 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-platform/resources/nvidia_driver/partial/_nvidia_driver_common.rb]: Removed the comment

File: cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb (hunk 12 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb:57]: Since this is in test code, can we address this later?

File: cookbooks/aws-parallelcluster-shared/libraries/test.rb (hunk 13 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-shared/libraries/test.rb:15]: Since this is in test code, can we address this later?

File: util/cinc-install.sh (hunk 18 above)
Comment (hanwen-pcluste) [reply util/cinc-install.sh]: Removed

File: cookbooks/aws-parallelcluster-environment/files/alinux2023/network_interfaces/configure_nw_interface.sh (hunk 20 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-environment/files/alinux2023/network_interfaces/configure_nw_interface.sh]: After testing, Amazon Linux 2023 does not require this script because amazon-ec2-net-utils is pre-installed in AL2023 and handles multi-nics instances properly.

`test_efa` has passed on multi-nics instances

File: kitchen/kitchen.run-hook.sh (hunk 17 above)
Comment (hanwen-pcluste) [reply kitchen/kitchen.run-hook.sh:40]: Since this is in test code, can we address this later?

File: cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb (hunk 12 above)
Comment (gmarciani) [reply cookbooks/aws-parallelcluster-platform/test/controls/dcv_spec.rb:57]: yes

File: cookbooks/aws-parallelcluster-shared/libraries/test.rb (hunk 13 above)
Comment (gmarciani) [reply cookbooks/aws-parallelcluster-shared/libraries/test.rb:15]: y

File: cookbooks/aws-parallelcluster-slurm/resources/mysql_client/partial/_setup_rhel_based.rb (hunk 15 above)
Comment (gmarciani) [reply cookbooks/aws-parallelcluster-slurm/resources/mysql_client/partial/_setup_rhel_based.rb:52]: Sure, the bad practice is doing:

```
platform_version = define platform version with meaning 1
if platform_version == 2
      platform_version = 7
use platform version with meaning 2
```

Not a blocking comment because the practice is not introduced in this PR, but better to address it at least in a follow up PR

File: cookbooks/aws-parallelcluster-environment/files/alinux2023/network_interfaces/configure_nw_interface.sh (hunk 20 above)
Comment (gmarciani) [reply cookbooks/aws-parallelcluster-environment/files/alinux2023/network_interfaces/configure_nw_interface.sh]: >Amazon Linux 2023 does not require this script
So we are removing the whole file, right?

File: cookbooks/aws-parallelcluster-environment/test/controls/system_authentication_spec.rb (hunk 6 above)
Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-environment/test/controls/system_authentication_spec.rb]: This change is not related to AL2023. I was a miss during redhat 9 support

File: cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb [hunk 21]
```diff
@@ -50,7 +50,9 @@
   cwd '/tmp'
   code <<-CUDA
     set -e
-    ./cuda.run --silent --toolkit --samples
+    mkdir /cuda-install
+    ./cuda.run --silent --toolkit --samples --tmpdir=/cuda-install
```
Comment (gmarciani) [inline cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb:54]: `/cuda-install` is meant to be a temporary directory, so we should create it under `/tmp`.
That said it's fine to use recursive deletion of that folder since it's a temp directory created by us and not meant ot be used by the user.

Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb:54]: `/tmp` on some OSes has size limit. That's why we had to change the directory

Comment (gmarciani) [reply cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb:54]: Then please add a comment on top of it to explain why we are not using tmp dir.
However, we should be in control of the tmp dir size and adjust it to our needs.
May you please track in the backlog the possibility to control the /tmp size as a separate partition (that is also a storage best practice)?

Comment (hanwen-pcluste) [reply cookbooks/aws-parallelcluster-platform/recipes/install/cuda.rb:54]: Done, added a comment

**Review by gmarciani — APPROVED** [review]
